site_name: My Docs
site_url: https://mydomain.org/mysite
theme:
  palette: 

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  name: material
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    # - toc.integrate
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy

plugins:
  - search
  - tags:
      tags_file: tags.md
  - blog    
      
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences


nav:
  - Home: index.md
  - Code docs: 
    - Java: coding/my-first-java-file.md
  - About: 
    - About me: about/about.md
    - sezione: about/sezione.md
  - tags: tags.md
  - blog: 
    - blog/index.md
